// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "myImage":return img`
..................
..........ffff....
.....ffffffeef....
.....feeeefeef....
.....ffeeeeeef....
......feeeeeff....
......feeeeef.....
......fdddddf.....
......fdfdfdf.....
......fdddddf.....
.....ffdddddf.....
.fffffdd111f......
fddff111ee1fff....
.fff1ffffffffff...
..fffdddddddffdf..
..fdfffffffdfdff..
..fddfdd11fffff...
..ffddddddddf.....
...ffffddddff.....
....ffffe8ff......
....f8ff8ef.......
....feefddf.......
....f8efd8f.......
.....ff.ff........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
..................
..........ffff....
.....ffffffeef....
.....feeeefeef....
.....ffeeeeeef....
......feeeeeff....
......feeeeef.....
......fdddddf.....
......fdfdfdf.....
......fdddddf.....
.....ffdddddf.....
.fffffdd11ef......
fddff1e1ee1fff....
.fff1deffffffff...
..ffeefdddddffdf..
..fd1e1ffffdfdff..
..fddfdd1efffff...
..ffddddddddf.....
...ffffddddff.....
....ffffe8ff......
....f8ff8ef.......
....feefddf.......
`, img`
..................
..........ffff....
.....ffffffeef....
.....feeeefeef....
.....ffeeeeeef....
......feeeeeff....
......feeeeef.....
......fdddddf.....
......fdfdfdf.....
......fdddddf.....
.....ffdddddf.....
..ffffdd111f......
.fdff111ee1fff....
.ffffffffffffff...
fdddddddddddffdf..
.ffffffffffdfdff..
..fddfdd11fffff...
..ffddddddddf.....
...ffffddddff.....
....ffffe8ff......
....f8ff8ef.......
....feefddf.......
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
